-- DEPRECATED: this file is no longer the source of truth.
--
-- The canonical CareStickers schema now lives in the Supabase CLI migrations:
--   supabase/migrations/0001_initial_schema.sql  (app tables; loaded by pg-mem, db.ts, Docker)
--   supabase/migrations/0002_auth_link.sql       (links public.users to Supabase auth.users)
--
-- Apply the schema with the Supabase CLI instead of this file:
--   npx supabase db push        # apply migrations to the linked project
--   npx supabase db reset        # rebuild the local DB from migrations + seed
--
-- This file is intentionally left as a no-op so any stale tooling that still reads it does
-- nothing rather than recreating an out-of-date schema.
